---
- name: test delegation
  hosts: testServer
  remote_user: vagrant
  become: yes

  tasks:
  - name: restart machine
    shell: sleep 2 && shutdown -r now "Ansible updates have been happened"
    async: 1
    poll: 0
    ignore_errors: True

  - name: waiting for server to come back
    wait_for: host={{inventory_hostname}} state=started delay=30 timeout=60
    become: no
    delegate_to: 127.0.0.1

